### ISSUE TITLE
도움! git push 권한 없음!

### ISSUE THREAD

**Issue by u-lo-l** [UNSEEN1st-AlgorithmStudy/PS#2]
![image](https://user-images.githubusercontent.com/60467872/227953309-5c52b6f8-b68e-4a80-a5d5-c5550bcea783.png)

Organization에 다른 레포 하나 만들어서 해봤더니 거기서는 push되는데 이 레포에서는 안 되네요 @HUSK-321

**Comment by u-lo-l** [comment]
혹시 fork해서 작업해야하나요

**Comment by HUSK-321** [comment]
아하 동호님 초대 받으신 후 권한을 안드려서 그런거 같습니다. 잠시만 기다려 주세요!

**Comment by HUSK-321** [comment]
Org 권한을 Owner로 변경했습니다!
아마 현재 푸쉬 잘 될것으로 보이는데 한번 해보시겠어요?

**Comment by u-lo-l** [comment]
일단 Fork하고 풀리퀘 쓰긴 했는데 다시 해볼게요
